name: Build Images

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.dataouest.net
          username: dataouestRegistryUser
          password: ${{ secrets.API_USER_PASSWORD }}

      - name: Checkout code repository
        uses: https://github.com/actions/checkout@v4

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."registry.dataouest.net"]
              http = true
              insecure = true

      - name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "registry.dataouest.net/dataouest/epilot:latest"

      - name: Build and push all Dockerfiles in subdirectories
        run: |
          for dir in */ ; do
            if [ -f "${dir}Dockerfile" ]; then
              image_name="registry.dataouest.net/dataouest/${dir%/}"
              echo "Building and pushing $image_name..."
              docker build -t "$image_name:latest" "$dir"
              docker push "$image_name:latest"
            fi
          done
